table T_ShipMode
	lineageTag: 94c4b627-54cd-46d8-9ff1-142e72832994

	column ShipModeId
		dataType: string
		lineageTag: 71618ae6-435c-4bdf-9dc5-1d5160bd85d8
		summarizeBy: none
		sourceColumn: ShipModeId

		annotation SummarizationSetBy = Automatic

	column ShipMode
		dataType: string
		lineageTag: 77179dd6-2f59-4496-922b-1d3194c0ef2a
		summarizeBy: none
		sourceColumn: ShipMode

		annotation SummarizationSetBy = Automatic

	partition T_ShipMode = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("d:\Users\Diego Ortiz\Documents\FREELANCE\cuesta\Home Assessment _ Data Viz\ShipMode.xlsx"), null, true),
				    Sheet1_Sheet = Origen{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ShipModeId", type text}, {"ShipMode", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

